FROM python:3.12-slim

RUN apt-get update && \
    apt-get install -y bash gnupg fonts-unifont && \
    apt-get install -y --no-install-recommends wkhtmltopdf && \
    rm -rf /var/lib/apt/lists/* && \
    pip3 install --upgrade pip
