name: Docker Build and Cleanup

on:
  push:
    branches:
      - master
    paths:
      - './Dockerfile.dockerbase'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Extract version number
        id: vars
        run: |
          echo "VERSION=$(date +%Y%m%d%H%M%S)" >> $GITHUB_ENV

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/strawall_base:${{ env.VERSION }} -f ./Dockerfile.dockerbase .
          docker tag ${{ secrets.DOCKERHUB_USERNAME }}/strawall_base:${{ env.VERSION }} ${{ secrets.DOCKERHUB_USERNAME }}/strawall_base:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/strawall_base:${{ env.VERSION }}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/strawall_base:latest

      - name: Cleanup old Docker images
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
        run: |
